
import { User, CareRequest } from './types';

export const TRANSLATIONS = {
  English: {
    // Shared
    welcome: "Welcome to CareCircle",
    tagline: "Connecting compassion across generations",
    selectLang: "Choose your preferred language",
    getStarted: "Get Started",
    login: "Log In",
    signup: "Sign Up",
    email: "Email Address",
    password: "Password",
    name: "Full Name",
    age: "Age",
    phone: "Phone Number",
    address: "Home Address",
    language: "Language",
    elder: "Elder",
    helper: "Helper",
    admin: "Admin",
    next: "Next",
    back: "Back",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    newUser: "New to CareCircle?",
    joinUs: "Join us today",
    logout: "Logout",
    welcomeUser: "Welcome",
    date: "Date",
    status: "Status",
    payment: "Payment",
    category: "Category",
    action: "Action",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    loading: "Loading...",
    underVerification: "Under Verification",
    verified: "Verified",
    rejected: "Rejected",

    // Categories
    Basic: "Basic Needs",
    Technical: "Technical Help",
    Personal: "Personal Escort",
    BasicDesc: "Daily Errands",
    TechnicalDesc: "Gadget Repair",
    PersonalDesc: "Paid Escort",

    // Statuses - Elder Perspective
    searching: "Searching for helper",
    assigned: "Helper assigned",
    on_the_way: "Helper on the way",
    in_progress: "Work in progress",
    completed: "Task completed",
    cancelled: "Cancelled",

    // Statuses - Helper Perspective
    h_searching: "Looking for tasks",
    h_assigned: "Task assigned to you",
    h_on_the_way: "You are on the way",
    h_in_progress: "Task in progress",
    h_completed: "Task completed successfully",

    // Elder Dashboard
    postNewNeed: "Post New Need",
    selectCategory: "Select Category",
    pickupAddress: "Location",
    dropAddress: "Delivery Address",
    destinationPoint: "Destination",
    distanceKm: "Distance (KM)",
    estHours: "Estimated Hours",
    requestDetails: "Request Details",
    addPhoto: "Add Photo",
    recordVoice: "Record Voice",
    stopRecord: "Stop Recording",
    transcribing: "Listening...",
    estFee: "Estimated Service Fee",
    submitRequest: "Submit Request",
    tracking: "Live Tracking",
    pastActivity: "History",
    noActiveTasks: "No active requests. Need help?",
    viewProgress: "View Progress",
    activityStatus: "Activity Status",
    realtimeUpdate: "Real-time update on your request",
    verifiedHelper: "Verified Helper",
    payRequest: "Pay Now",
    paymentConfirmed: "Payment Successful",
    rateHelper: "Rate Helper",
    rateTitle: "Rate the Service",
    rateDesc: "Your feedback helps helpers earn levels.",
    howWasService: "How was the service?",
    finishRate: "Submit Rating",

    // Helper Dashboard
    profileUnderReview: "Profile under admin verification",
    verificationPending: "Our safety team is validating your documents.",
    verifiedSuccess: "Tasks Completed",
    paidRatedOnly: "Paid & Rated",
    clearedEarnings: "Total Earnings",
    processing: "Pending",
    activeTier: "Your Level",
    officialRecognition: "Certificates",
    moreNeeded: "more tasks needed",
    unlockCert: "Complete 3 tasks to unlock certificate.",
    downloadCert: "Download Certificate",
    activeTab: "Assigned",
    nearbyTab: "Nearby",
    historyTab: "Logs",
    onMyWay: "Start Travel",
    startService: "Start Work",
    markFinished: "Finish Work",
    elderAttachedPhoto: "Elder's Photo",
    internshipTask: "Internship Training",
    advancedBasic: "Professional Task",
    callElder: "Call Elder",
    noAssignedTasks: "No assigned tasks yet.",
    browseOpportunities: "Browse nearby tasks",
    noTasksMatch: "No tasks available for your level.",
    studentNote: "Students: Only short basic tasks (≤4km/3hr).",
    helperNote: "Advanced tasks: >4km or professional categories.",
    confirmedPaid: "Paid",
    pendingElderAction: "Payment Pending",
    ratingPending: "Rating Pending",

    // Admin Dashboard
    totalHelpers: "Total Helpers",
    serviceRequests: "All Requests",
    totalVolume: "Total Volume",
    helpersTab: "Verification",
    tasksTab: "All Tasks",
    helperVerification: "Helper Approval",
    searchHelpers: "Search by name...",
    helperIdentity: "Helper Info",
    idVerification: "ID Proofs",
    viewProofs: "View Files",
    liveActivity: "Platform Activity",
    verificationDocs: "ID Documents",
    doneReviewing: "Finished Review",
    approve: "Approve",
    reject: "Reject"
  },
  Tamil: {
    // Shared
    welcome: "கேர்-சர்க்கிள்-க்கு வரவேற்கிறோம்",
    tagline: "தலைமுறைகளை அன்பால் இணைக்கிறோம்",
    selectLang: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    getStarted: "தொடங்குவோம்",
    login: "உள்நுழைக",
    signup: "பதிவு செய்க",
    email: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    name: "முழு பெயர்",
    age: "வயது",
    phone: "தொலைபேசி எண்",
    address: "வீட்டு முகவரி",
    language: "மொழி",
    elder: "பெரியவர்",
    helper: "உதவியாளர்",
    admin: "நிர்வாகி",
    next: "அடுத்து",
    back: "பின்செல்",
    createAccount: "கணக்கை உருவாக்கு",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    newUser: "புதியவரா?",
    joinUs: "இன்றே இணையுங்கள்",
    logout: "வெளியேறு",
    welcomeUser: "வரவேற்கிறோம்",
    date: "தேதி",
    status: "நிலை",
    payment: "கட்டணம்",
    category: "வகை",
    action: "செயல்",
    save: "சேமி",
    cancel: "ரத்து செய்",
    close: "மூடு",
    loading: "ஏற்றப்படுகிறது...",
    underVerification: "சரிபார்ப்பில் உள்ளது",
    verified: "சரிபார்க்கப்பட்டது",
    rejected: "நிராகரிக்கப்பட்டது",

    // Categories
    Basic: "அடிப்படைத் தேவை",
    Technical: "தொழில்நுட்ப உதவி",
    Personal: "துணை மற்றும் உதவி",
    BasicDesc: "தினசரி பணிகள்",
    TechnicalDesc: "சாதனங்கள் பழுது",
    PersonalDesc: "கட்டண துணை",

    // Statuses - Elder Perspective
    searching: "உதவியாளரை தேடுகிறது",
    assigned: "உதவியாளர் ஒதுக்கப்பட்டு விட்டார்",
    on_the_way: "உதவியாளர் வந்து கொண்டிருக்கிறார்",
    in_progress: "பணி நடைபெறுகிறது",
    completed: "பணி முடிந்துவிட்டது",
    cancelled: "ரத்து செய்யப்பட்டது",

    // Statuses - Helper Perspective
    h_searching: "பணிகளைத் தேடுகிறது",
    h_assigned: "பணி உங்களுக்கு ஒதுக்கப்பட்டுள்ளது",
    h_on_the_way: "நீங்கள் வந்து கொண்டிருக்கிறீர்கள்",
    h_in_progress: "பணி நடைபெறுகிறது",
    h_completed: "பணி வெற்றிகரமாக முடிந்தது",

    // Elder Dashboard
    postNewNeed: "புதிய தேவையை இடுகையிடவும்",
    selectCategory: "வகையைத் தேர்ந்தெடுக்கவும்",
    pickupAddress: "இடம்",
    dropAddress: "டெலிவரி முகவரி",
    destinationPoint: "சேருமிடம்",
    distanceKm: "தூரம் (கி.மீ)",
    estHours: "மதிப்பிடப்பட்ட நேரம்",
    requestDetails: "தேவை பற்றிய விவரம்",
    addPhoto: "புகைப்படம் சேர்",
    recordVoice: "குரல் பதிவு",
    stopRecord: "பதிவை நிறுத்து",
    transcribing: "கேட்டுக் கொண்டிருக்கிறது...",
    estFee: "மதிப்பிடப்பட்ட கட்டணம்",
    submitRequest: "கோரிக்கையை சமர்ப்பிக்கவும்",
    tracking: "நேரடி கண்காணிப்பு",
    pastActivity: "வரலாறு",
    noActiveTasks: "கோரிக்கைகள் எதுவும் இல்லை. உதவி தேவையா?",
    viewProgress: "நிலையை பார்க்க",
    activityStatus: "செயல்பாட்டு நிலை",
    realtimeUpdate: "உங்கள் கோரிக்கையின் நேரடி நிலவரம்",
    verifiedHelper: "சரிபார்க்கப்பட்ட உதவியாளர்",
    payRequest: "இப்போது கட்டணம் செலுத்து",
    paymentConfirmed: "கட்டணம் வெற்றிகரமாக செலுத்தப்பட்டது",
    rateHelper: "மதிப்பீடு செய்",
    rateTitle: "சேவையை மதிப்பிடவும்",
    rateDesc: "உங்கள் கருத்து உதவியாளர்கள் முன்னேற உதவும்.",
    howWasService: "சேவை எப்படி இருந்தது?",
    finishRate: "மதிப்பீட்டை சமர்ப்பி",

    // Helper Dashboard
    profileUnderReview: "சுயவிவரம் சரிபார்ப்பில் உள்ளது",
    verificationPending: "எங்கள் குழு உங்கள் ஆவணங்களை சரிபார்த்து வருகிறது.",
    verifiedSuccess: "முடிக்கப்பட்ட பணிகள்",
    paidRatedOnly: "கட்டணம் மற்றும் மதிப்பீடு",
    clearedEarnings: "மொத்த வருமானம்",
    processing: "நிலுவையில்",
    activeTier: "உங்கள் நிலை",
    officialRecognition: "சான்றிதழ்கள்",
    moreNeeded: "பணிகள் இன்னும் தேவை",
    unlockCert: "சான்றிதழைப் பெற 3 பணிகளை முடிக்கவும்.",
    downloadCert: "சான்றிதழைப் பதிவிறக்கு",
    activeTab: "ஒதுக்கப்பட்டவை",
    nearbyTab: "அருகிலுள்ளவை",
    historyTab: "பதிவுகள்",
    onMyWay: "பயணத்தைத் தொடங்கு",
    startService: "பணியைத் தொடங்கு",
    markFinished: "பணியை முடி",
    elderAttachedPhoto: "பெரியவர் இணைத்த படம்",
    internshipTask: "பயிற்சிப் பணி",
    advancedBasic: "தொழில்முறைப் பணி",
    callElder: "பெரியவரை அழைக்கவும்",
    noAssignedTasks: "பணிகள் எதுவும் ஒதுக்கப்படவில்லை.",
    browseOpportunities: "அருகிலுள்ள பணிகளைத் தேடு",
    noTasksMatch: "உங்கள் நிலைக்கு ஏற்ற பணிகள் இல்லை.",
    studentNote: "மாணவர்கள்: 4கிமீ/3மணிநேரத்திற்குள் உள்ள பணிகள் மட்டும்.",
    helperNote: "கூடுதல் பணிகள்: >4கிமீ அல்லது தொழில்முறை பிரிவுகள்.",
    confirmedPaid: "செலுத்தப்பட்டது",
    pendingElderAction: "கட்டணம் நிலுவையில் உள்ளது",
    ratingPending: "மதிப்பீடு நிலுவையில் உள்ளது",

    // Admin Dashboard
    totalHelpers: "மொத்த உதவியாளர்கள்",
    serviceRequests: "அனைத்து கோரிக்கைகள்",
    totalVolume: "மொத்த வருவாய்",
    helpersTab: "சரிபார்ப்பு",
    tasksTab: "அனைத்து பணிகள்",
    helperVerification: "உதவியாளர் அனுமதி",
    searchHelpers: "பெயர் மூலம் தேடு...",
    helperIdentity: "உதவியாளர் விவரம்",
    idVerification: "அடையாளச் சான்றுகள்",
    viewProofs: "ஆவணங்களைப் பார்க்க",
    liveActivity: "நேரடி செயல்பாடு",
    verificationDocs: "அடையாள ஆவணங்கள்",
    doneReviewing: "சரிபார்த்து முடிந்தது",
    approve: "அனுமதி",
    reject: "நிராகரி"
  }
};

export const INITIAL_USERS: User[] = [
  {
    id: 'admin-1',
    role: 'admin',
    name: 'CareCircle Admin',
    email: 'admin@carecircle.com',
    password: 'password123',
    phone: '9876543210',
    age: 30,
    language: 'English',
    avatar: 'A'
  },
  {
    id: 'elder-demo',
    role: 'elder',
    name: 'Prakash Rao',
    email: 'elder@demo.com',
    password: 'password123',
    phone: '9988776655',
    age: 72,
    language: 'Tamil',
    avatar: 'P',
    address: '42, Adyar, Chennai'
  }
];

export const INITIAL_REQUESTS: CareRequest[] = [];

export const CATEGORY_STYLES = {
  Basic: 'bg-blue-100 text-blue-700 border-blue-200',
  Technical: 'bg-purple-100 text-purple-700 border-purple-200',
  Personal: 'bg-emerald-100 text-emerald-700 border-emerald-200'
};

export const STATUS_STYLES = {
  searching: 'bg-yellow-100 text-yellow-700',
  assigned: 'bg-blue-100 text-blue-700',
  on_the_way: 'bg-indigo-100 text-indigo-700',
  in_progress: 'bg-orange-100 text-orange-700',
  completed: 'bg-green-100 text-green-700',
  cancelled: 'bg-red-100 text-red-700'
};
